### ISSUE TITLE
Kubernetes manifests

### ISSUE THREAD

**Issue by swade1987** [EddieJaoudeCommunity/LiveStream-GitOps-Demo#4]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-node-app
  namespace: example-node-app
  labels:
    name: example-node-app
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 30
  selector:
    matchLabels:
      app_name: example-node-app
      app_version: 1.1.1
  template:
    metadata:
      labels:
        app_name: example-node-app
        app_version: 1.1.1
    spec:
      containers:
        - name: example-node-app
          image: quay.io/swade1987/example-node-app:1.1.1
          ports:
            - containerPort: 3000
          # is the container online (e.g. has it booted successfully?)
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          # is the container ready to receive traffic?
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 10
```

```
apiVersion: v1
kind: Namespace
metadata:
  name: example-node-app
```

```
apiVersion: v1
kind: Service
metadata:
  name: examples-node-app
  namespace: example-node-app
  labels:
    name: example-node-app
spec:
  selector:             # selects pods with these labels
    app_name: example-node-app
    app_version: 1.1.1
  type: NodePort
  ports:
    - name: http
      port: 80          # service port
      protocol: TCP
      targetPort: 3000  # pod port
```
